const source = (language, operation = 'double', complete = false) => {
  if (language === 'python') return operation === 'double'
    ? `numero = int(input())\n${complete ? 'print(numero * 2)' : '# Mostre o dobro do número'}\n`
    : 'preco = int(input())\nquantidade = int(input())\n# Mostre o custo total\n';
  return `import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner entrada = new Scanner(System.in);\n${operation === 'double' ? '        int numero = entrada.nextInt();\n        // Mostre o dobro do número' : '        int preco = entrada.nextInt();\n        int quantidade = entrada.nextInt();\n        // Mostre o custo total'}\n    }\n}\n`;
};
export function programmingDemo(language) {
  const label = language === 'python' ? 'Python' : 'Java';
  const example = language === 'python' ? 'idade = int(input())\nproxima_idade = idade + 1\nprint(proxima_idade)' : 'import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner entrada = new Scanner(System.in);\n        int idade = entrada.nextInt();\n        int proximaIdade = idade + 1;\n        System.out.println(proximaIdade);\n    }\n}';
  return {
    session: { title: `Primeiros programas em ${label}`, goal: 'Ler dados, transformar um número e resolver uma variação sem copiar.', level: 'beginner', objectives: ['Distinguir entrada, processamento e saída', 'Transformar entradas em números', 'Adaptar o cálculo a outro contexto'], timeBudgetMinutes: 25 },
    intro: { type: 'lesson', stage: 'learn', title: 'Entrada → transformação → saída', concept: 'Entrada, processamento e saída', body: `Um programa recebe dados, transforma esses dados e apresenta um resultado. Em ${label}, você pode ler um número do console, guardar esse valor em uma variável e calcular com ele. Esta aula é um roteiro guiado, sem IA: os testes conferem resultados e suas explicações ficam salvas.`, takeaways: ['A entrada informa o valor usado pelo programa.', 'Uma variável guarda um valor para ser reutilizado.', 'A saída deve mostrar o resultado do cálculo.'], example: { language, code: example, explanation: 'Exemplo resolvido: com entrada 20, a variável recebe 20. Somamos 1 e mostramos 21. Observe como cada linha participa desse percurso. No exercício, você vai usar uma transformação diferente.' } },
    prediction: { type: 'quiz', stage: 'predict', title: 'Faça uma previsão', prompt: 'No exemplo acima, se a entrada for 9, qual número aparece na saída?', options: ['9', '10', '91'], correctIndex: 1, explanation: 'A entrada vira um número. O programa soma 1, portanto 9 + 1 = 10.', hints: ['A conversão permite somar números. Não estamos juntando dois textos.'] },
    practice: { type: 'code', language, stage: 'practice', concept: 'Entrada, processamento e saída', title: 'Sua vez: transforme o número', prompt: 'Leia um número inteiro e mostre o dobro. Execute com diferentes entradas antes de enviar. Explique qual parte recebe o número e qual faz o cálculo. Mostre somente o resultado, sem uma mensagem extra.', starterCode: source(language), stdin: '3', tests: [{ name: 'Número positivo', stdin: '3', expectedStdout: '6' }, { name: 'Zero', stdin: '0', expectedStdout: '0' }, { name: 'Número negativo', stdin: '-4', expectedStdout: '-8' }], hints: ['Você já recebeu o número na variável numero. Falta transformar e mostrar.', language === 'python' ? 'Use a multiplicação por 2 e mostre o resultado com print.' : 'Use a multiplicação por 2 e mostre o resultado com System.out.println.'] },
    structure: { type: 'diagram', stage: 'explain', title: 'Acompanhe o valor', caption: 'Selecione uma etapa e explique o caminho que o dado percorre.', nodes: [{ id: 'input', label: 'Entrada', detail: 'O aluno informa um número, por exemplo 3.' }, { id: 'variable', label: 'Variável', detail: 'O valor é lido como número e guardado para o cálculo.' }, { id: 'process', label: 'Cálculo', detail: 'O programa multiplica o número por 2.' }, { id: 'output', label: 'Saída', detail: 'O resultado 6 aparece no console.' }], edges: [{ from: 'input', to: 'variable' }, { from: 'variable', to: 'process' }, { from: 'process', to: 'output' }] },
    reflection: { type: 'reflection', stage: 'explain', title: 'Explique a transformação', prompt: 'Se a entrada mudar de 3 para 8, quais valores mudam durante a execução? Explique sem apenas copiar o programa. Sua explicação será registrada para discussão com o tutor, sem correção simulada.' },
    transfer: { type: 'code', language, stage: 'transfer', concept: 'Entrada, processamento e saída', title: 'Aplique em uma pequena loja', prompt: 'Agora leia dois inteiros, um em cada linha: preço e quantidade. Mostre o custo total. Comece com a estrutura de entrada e encontre a transformação por conta própria. Qual ideia do exercício anterior você reutilizou?', starterCode: source(language, 'shop'), stdin: '7\n3', tests: [{ name: 'Três itens de 7', stdin: '7\n3', expectedStdout: '21' }, { name: 'Quantidade zero', stdin: '5\n0', expectedStdout: '0' }, { name: 'Um item', stdin: '12\n1', expectedStdout: '12' }], hints: ['O total depende dos dois valores recebidos. Pense na operação que representa repetir o preço para cada item.'] },
    review: { concept: 'Entrada, processamento e saída', prompt: 'Sem consultar o exemplo, descreva os três passos de um programa que recebe um número e mostra seu triplo. Por que é importante ler esse valor como número?', referenceAnswer: 'Primeiro ler a entrada como número; depois calcular o valor multiplicado por 3; por fim mostrar o resultado. A representação numérica permite operações aritméticas, em vez de simplesmente juntar textos.' },
  };
}
